name: Coughy
options:
  bundleIdPrefix: com.coughy
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"

targets:
  CoughyPhone:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Phone
        excludes:
          - Resources/Info.plist
          - Resources/coughy.svg
          - Resources/sleep.svg
      - path: Models/CoughCNN.mlpackage
        type: file
    # di-comment agar tidak memerlukan developer account
#    entitlements:
#      path: Sources/Phone/Resources/Coughy.entitlements
#      properties:
#        com.apple.developer.healthkit: true
    dependencies:
      - sdk: HealthKit.framework
      - sdk: PDFKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.coughy
        SWIFT_VERSION: "5.9"
    info:
      path: Sources/Phone/Resources/Info.plist
      properties:
        CFBundleDisplayName: Coughy
        NSMicrophoneUsageDescription: "Coughy uses the microphone to monitor for coughs during sleep."
        NSHealthShareUsageDescription: "Coughy reads Health data to correlate cough activity with your vitals."
        NSHealthUpdateUsageDescription: "Coughy writes heart rate and weight data to Apple Health."
        UIBackgroundModes:
          - audio
        UILaunchScreen: {}
